export interface PacienteResponse{
    ok:        boolean;
    paciente: Paciente[];
}


export interface PacientesResponse{
    ok:        boolean;
    pacientes: Paciente[];
}

export interface Paciente {
    idPaciente:          string;
    Modalidad:           string;
    FechaNacimiento:     null;
    Cedula:              string;
    TelCel:              null;
    FechaInicioPrograma: null;
    Equipo:              null;
    TipoEquipo:          null;
    MarcaEquipo:         null;
    ModeloEquipo:        null;
    SerieEquipo:         null;
    MarcaMascarilla:     null;
    TallaMascarilla:     null;
    ModeloMascarilla:    null;
    NoContrato:          null;
    IdTerapeuta:         string;
    MedicoTratante:      null;
    Observaciones:       null;
    NombrePaciente:      string;
    Direccion:           null;
    Hospital:            string;
    FotoPaciente:        null;
}



// Generated by https://quicktype.io

export interface VisitasResponse {
    ok:                boolean;
    VisitasHospitales: VisitasHospitales[];
    msg:               string;
}

export interface VisitaResponse {
    ok:                boolean;
    VisitasHospital: VisitasHospital;
    msg:               string;
}

export interface VisitasHospital {
    Id:                         string;
    deleted:                    null;
    IdHospital:                 string;
    idPaciente:                 string;
    IdTerapeuta:                string;
    IdMesVisita:                string;
    FechaVisita:                string;
    IdTipoVisita:               string;
    IdTipoEquipo:               string;
    FrecuenciaCardiaca:         string;
    PresionArterialSistolica:   string;
    PresionArterialDiastolica:  string;
    SaturacionOxigeno:          string;
    HoraUsoPromDia:             string;
    HorasTotalMensuales:        string;
    DiasUsoSobreTotal:          string;
    FugaLmin:                   string;
    IndiceApnea:                string;
    PresionUtilizadaEpap:       string;
    PresionUtilizadaIPAP:       string;
    PresionUtilizadaCPAP:       string;
    CambioEquipo:               boolean;
    NumSerieEquipoyDN:          string;
    IdEstadoEquipo:             string;
    IdEvaluacionVisita:         string;
    ObservacionesClinicas:      string;
    ComentariosAdministrativos: string;
    SharePoint:                 boolean;
    EstadoPaciente : string,
    AdherenciaUsoTratamiento: string,
    CambEquiInsuTrata: string,
    CondTrataYParam: string,
    SituaEspecYCoordi: string,
    createdAt:                  null;
    updatedAt:                  null;
}


export interface VisitasHospitales {
    Id: string;
    createdAt?: Date;
    updatedAt?: Date;
    deleted?: string;
    IdHospital?: string;
    DscHospital?: string;
    idPaciente?: string;
    NombrePaciente: string;
    IdTerapeuta?: string;
    NombreTerapeuta?: string;
    IdMesVisita?: string;
    DscMesVisita?: string;
    FechaVisita?: string ;
    IdTipoVisita?: string;
    DscTipoVisita?: string;
    IdTipoEquipo?: string;
    DscTipoEquipo?: string;
    FrecuenciaCardiaca?: string;
    PresionArterialSistolica?: string;
    PresionArterialDiastolica?: string;
    SaturacionOxigeno?: string;
    HoraUsoPromDia?: string;
    HorasTotalMensuales?: string;
    DiasUsoSobreTotal?: string;
    FugaLmin?: string;
    IndiceApnea?: string;
    PresionUtilizadaEpap?: string;
    PresionUtilizadaIPAP?: string;
    PresionUtilizadaCPAP?: string;
    CambioEquipo?: boolean;
    NumSerieEquipoyDN?: string;
    IdEstadoEquipo?: string;
    DscEstadoEquipo?: string;
    IdEvaluacionVisita?: string;
    DscEvaluacionVisitas?: string;
    ObservacionesClinicas?: string;
    ComentariosAdministrativos?: string;
    SharePoint?: boolean;
    EstadoPaciente : string,
    DsEstadoPaciente : string,
    AdherenciaUsoTratamiento: string,
    DsAdherenciaUsoTratamiento: string,
    CambEquiInsuTrata: string,
    DsCambEquiInsuTrata: string,
    CondTrataYParam: string,
    DsCondTrataYParam: string,
    SituaEspecYCoordi: string,
    DsSituaEspecYCoordi: string,

  }


  // Generated by https://quicktype.io

export interface TiposVisitaResponse {
    ok:           boolean;
    tiposvisitas: Tiposvisita[];
    msg:          string;
}

export interface Tiposvisita {
    IdTipoVisita:  string;
    DscTipoVisita: string;
}



export interface ReferenciasResponse {
    ok:           boolean;
    msg:          string;
    Referencias: Referencia[];
   
}

export interface Referencia {
    IdReferencia:  number;
    IdTipoReferencia: string;
    DsReferencica: string;
}


// Generated by https://quicktype.io

export interface EstadosEquipoResponse {
    ok:             boolean;
    EstadosEquipos: EstadosEquipo[];
    msg:            string;
}

export interface EstadosEquipo {
    IdEstadoEquipo:  string;
    DscEstadoEquipo: string;
}

// Generated by https://quicktype.io

export interface MesesVisitasResponse {
    ok:           boolean;
    MesesVisitas: MesesVisita[];
    msg:          string;
}

export interface MesesVisita {
    IdMesVisita:  string;
    DscMesVisita: string;
}

// Generated by https://quicktype.io

export interface HospitalesResponse {
    ok:         boolean;
    Hospitales: Hospitales[];
    msg:        string;
}

export interface Hospitales {
    IdHospital:  string;
    DscHospital: string;
}

// Generated by https://quicktype.io

export interface EvaluacionVisitaResponse {
    ok:                boolean;
    EvaluacionVisitas: EvaluacionVisita[];
    msg:               string;
}

export interface EvaluacionVisita {
    IdEvaluacionVisita:   string;
    DscEvaluacionVisitas: string;
}


// Generated by https://quicktype.io

export interface TiposEquiposResponse {
    ok:           boolean;
    TiposEquipos: TiposEquipo[];
    msg:          string;
}

export interface TiposEquipo {
    IdTipoEquipo:  string;
    DscTipoEquipo: string;
}
